sudo: false
language: scala
script:
  - sbt ++${TRAVIS_SCALA_VERSION} clean update compile test
matrix:
  include:
  - scala: 2.11.8
    jdk: openjdk6
    env: IS_PUBLISH_JDK=true
  - scala: 2.12.0
    jdk: oraclejdk8
    env: IS_PUBLISH_JDK=true
notifications:
  email:
    - adriaan.moors@lightbend.com
